apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: sentinelpay
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/part-of: sentinelpay
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: payment-service
  ports:
    - port: 8081
      targetPort: 8081
      name: http
